import 'language.dart';
import 'model.dart';

/// 从英语到其他语言的模型文件映射（完整版）
final fromEnglishFiles = {
  Language.albanian: LanguageFiles(
    model: 'model.ensq.intgemm.alphas.bin',
    srcVocab: 'vocab.ensq.spm',
    tgtVocab: 'vocab.ensq.spm',
    lex: 'lex.50.50.ensq.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.arabic: LanguageFiles(
    model: 'model.enar.intgemm.alphas.bin',
    srcVocab: 'vocab.enar.spm',
    tgtVocab: 'vocab.enar.spm',
    lex: 'lex.50.50.enar.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.azerbaijani: LanguageFiles(
    model: 'model.enaz.intgemm.alphas.bin',
    srcVocab: 'vocab.enaz.spm',
    tgtVocab: 'vocab.enaz.spm',
    lex: 'lex.50.50.enaz.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.bengali: LanguageFiles(
    model: 'model.enbn.intgemm.alphas.bin',
    srcVocab: 'vocab.enbn.spm',
    tgtVocab: 'vocab.enbn.spm',
    lex: 'lex.50.50.enbn.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.bulgarian: LanguageFiles(
    model: 'model.enbg.intgemm.alphas.bin',
    srcVocab: 'vocab.enbg.spm',
    tgtVocab: 'vocab.enbg.spm',
    lex: 'lex.50.50.enbg.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.catalan: LanguageFiles(
    model: 'model.enca.intgemm.alphas.bin',
    srcVocab: 'vocab.enca.spm',
    tgtVocab: 'vocab.enca.spm',
    lex: 'lex.50.50.enca.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.chinese: LanguageFiles(
    model: 'model.enzh.intgemm.alphas.bin',
    srcVocab: 'srcvocab.enzh.spm',
    tgtVocab: 'trgvocab.enzh.spm',
    lex: 'lex.50.50.enzh.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.croatian: LanguageFiles(
    model: 'model.enhr.intgemm.alphas.bin',
    srcVocab: 'vocab.enhr.spm',
    tgtVocab: 'vocab.enhr.spm',
    lex: 'lex.50.50.enhr.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.czech: LanguageFiles(
    model: 'model.encs.intgemm.alphas.bin',
    srcVocab: 'vocab.encs.spm',
    tgtVocab: 'vocab.encs.spm',
    lex: 'lex.50.50.encs.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.danish: LanguageFiles(
    model: 'model.enda.intgemm.alphas.bin',
    srcVocab: 'vocab.enda.spm',
    tgtVocab: 'vocab.enda.spm',
    lex: 'lex.50.50.enda.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.dutch: LanguageFiles(
    model: 'model.ennl.intgemm.alphas.bin',
    srcVocab: 'vocab.ennl.spm',
    tgtVocab: 'vocab.ennl.spm',
    lex: 'lex.50.50.ennl.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.estonian: LanguageFiles(
    model: 'model.enet.intgemm.alphas.bin',
    srcVocab: 'vocab.enet.spm',
    tgtVocab: 'vocab.enet.spm',
    lex: 'lex.50.50.enet.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.finnish: LanguageFiles(
    model: 'model.enfi.intgemm.alphas.bin',
    srcVocab: 'vocab.enfi.spm',
    tgtVocab: 'vocab.enfi.spm',
    lex: 'lex.50.50.enfi.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.french: LanguageFiles(
    model: 'model.enfr.intgemm.alphas.bin',
    srcVocab: 'vocab.enfr.spm',
    tgtVocab: 'vocab.enfr.spm',
    lex: 'lex.50.50.enfr.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.german: LanguageFiles(
    model: 'model.ende.intgemm.alphas.bin',
    srcVocab: 'vocab.ende.spm',
    tgtVocab: 'vocab.ende.spm',
    lex: 'lex.50.50.ende.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.greek: LanguageFiles(
    model: 'model.enel.intgemm.alphas.bin',
    srcVocab: 'vocab.enel.spm',
    tgtVocab: 'vocab.enel.spm',
    lex: 'lex.50.50.enel.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.gujarati: LanguageFiles(
    model: 'model.engu.intgemm.alphas.bin',
    srcVocab: 'vocab.engu.spm',
    tgtVocab: 'vocab.engu.spm',
    lex: 'lex.50.50.engu.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.hebrew: LanguageFiles(
    model: 'model.enhe.intgemm.alphas.bin',
    srcVocab: 'vocab.enhe.spm',
    tgtVocab: 'vocab.enhe.spm',
    lex: 'lex.50.50.enhe.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.hindi: LanguageFiles(
    model: 'model.enhi.intgemm.alphas.bin',
    srcVocab: 'vocab.enhi.spm',
    tgtVocab: 'vocab.enhi.spm',
    lex: 'lex.50.50.enhi.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.hungarian: LanguageFiles(
    model: 'model.enhu.intgemm.alphas.bin',
    srcVocab: 'vocab.enhu.spm',
    tgtVocab: 'vocab.enhu.spm',
    lex: 'lex.50.50.enhu.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.icelandic: LanguageFiles(
    model: 'model.enis.intgemm.alphas.bin',
    srcVocab: 'vocab.enis.spm',
    tgtVocab: 'vocab.enis.spm',
    lex: 'lex.50.50.enis.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.indonesian: LanguageFiles(
    model: 'model.enid.intgemm.alphas.bin',
    srcVocab: 'vocab.enid.spm',
    tgtVocab: 'vocab.enid.spm',
    lex: 'lex.50.50.enid.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.italian: LanguageFiles(
    model: 'model.enit.intgemm.alphas.bin',
    srcVocab: 'vocab.enit.spm',
    tgtVocab: 'vocab.enit.spm',
    lex: 'lex.50.50.enit.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.japanese: LanguageFiles(
    model: 'model.enja.intgemm.alphas.bin',
    srcVocab: 'srcvocab.enja.spm',
    tgtVocab: 'trgvocab.enja.spm',
    lex: 'lex.50.50.enja.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.kannada: LanguageFiles(
    model: 'model.enkn.intgemm.alphas.bin',
    srcVocab: 'vocab.enkn.spm',
    tgtVocab: 'vocab.enkn.spm',
    lex: 'lex.50.50.enkn.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.korean: LanguageFiles(
    model: 'model.enko.intgemm.alphas.bin',
    srcVocab: 'srcvocab.enko.spm',
    tgtVocab: 'trgvocab.enko.spm',
    lex: 'lex.50.50.enko.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.latvian: LanguageFiles(
    model: 'model.enlv.intgemm.alphas.bin',
    srcVocab: 'vocab.enlv.spm',
    tgtVocab: 'vocab.enlv.spm',
    lex: 'lex.50.50.enlv.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.lithuanian: LanguageFiles(
    model: 'model.enlt.intgemm.alphas.bin',
    srcVocab: 'vocab.enlt.spm',
    tgtVocab: 'vocab.enlt.spm',
    lex: 'lex.50.50.enlt.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.malay: LanguageFiles(
    model: 'model.enms.intgemm.alphas.bin',
    srcVocab: 'vocab.enms.spm',
    tgtVocab: 'vocab.enms.spm',
    lex: 'lex.50.50.enms.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.malayalam: LanguageFiles(
    model: 'model.enml.intgemm.alphas.bin',
    srcVocab: 'vocab.enml.spm',
    tgtVocab: 'vocab.enml.spm',
    lex: 'lex.50.50.enml.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.persian: LanguageFiles(
    model: 'model.enfa.intgemm.alphas.bin',
    srcVocab: 'vocab.enfa.spm',
    tgtVocab: 'vocab.enfa.spm',
    lex: 'lex.50.50.enfa.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.polish: LanguageFiles(
    model: 'model.enpl.intgemm.alphas.bin',
    srcVocab: 'vocab.enpl.spm',
    tgtVocab: 'vocab.enpl.spm',
    lex: 'lex.50.50.enpl.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.portuguese: LanguageFiles(
    model: 'model.enpt.intgemm.alphas.bin',
    srcVocab: 'vocab.enpt.spm',
    tgtVocab: 'vocab.enpt.spm',
    lex: 'lex.50.50.enpt.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.romanian: LanguageFiles(
    model: 'model.enro.intgemm.alphas.bin',
    srcVocab: 'vocab.enro.spm',
    tgtVocab: 'vocab.enro.spm',
    lex: 'lex.50.50.enro.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.russian: LanguageFiles(
    model: 'model.enru.intgemm.alphas.bin',
    srcVocab: 'vocab.enru.spm',
    tgtVocab: 'vocab.enru.spm',
    lex: 'lex.50.50.enru.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.slovak: LanguageFiles(
    model: 'model.ensk.intgemm.alphas.bin',
    srcVocab: 'vocab.ensk.spm',
    tgtVocab: 'vocab.ensk.spm',
    lex: 'lex.50.50.ensk.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.slovenian: LanguageFiles(
    model: 'model.ensl.intgemm.alphas.bin',
    srcVocab: 'vocab.ensl.spm',
    tgtVocab: 'vocab.ensl.spm',
    lex: 'lex.50.50.ensl.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.spanish: LanguageFiles(
    model: 'model.enes.intgemm.alphas.bin',
    srcVocab: 'vocab.enes.spm',
    tgtVocab: 'vocab.enes.spm',
    lex: 'lex.50.50.enes.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.swedish: LanguageFiles(
    model: 'model.ensv.intgemm.alphas.bin',
    srcVocab: 'vocab.ensv.spm',
    tgtVocab: 'vocab.ensv.spm',
    lex: 'lex.50.50.ensv.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.tamil: LanguageFiles(
    model: 'model.enta.intgemm.alphas.bin',
    srcVocab: 'vocab.enta.spm',
    tgtVocab: 'vocab.enta.spm',
    lex: 'lex.50.50.enta.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.telugu: LanguageFiles(
    model: 'model.ente.intgemm.alphas.bin',
    srcVocab: 'vocab.ente.spm',
    tgtVocab: 'vocab.ente.spm',
    lex: 'lex.50.50.ente.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.turkish: LanguageFiles(
    model: 'model.entr.intgemm.alphas.bin',
    srcVocab: 'vocab.entr.spm',
    tgtVocab: 'vocab.entr.spm',
    lex: 'lex.50.50.entr.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.ukrainian: LanguageFiles(
    model: 'model.enuk.intgemm.alphas.bin',
    srcVocab: 'vocab.enuk.spm',
    tgtVocab: 'vocab.enuk.spm',
    lex: 'lex.50.50.enuk.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
};

/// 从其他语言到英语的模型文件映射（完整版）
final toEnglishFiles = {
  Language.albanian: LanguageFiles(
    model: 'model.sqen.intgemm.alphas.bin',
    srcVocab: 'vocab.sqen.spm',
    tgtVocab: 'vocab.sqen.spm',
    lex: 'lex.50.50.sqen.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.arabic: LanguageFiles(
    model: 'model.aren.intgemm.alphas.bin',
    srcVocab: 'vocab.aren.spm',
    tgtVocab: 'vocab.aren.spm',
    lex: 'lex.50.50.aren.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.azerbaijani: LanguageFiles(
    model: 'model.azen.intgemm.alphas.bin',
    srcVocab: 'vocab.azen.spm',
    tgtVocab: 'vocab.azen.spm',
    lex: 'lex.50.50.azen.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.bengali: LanguageFiles(
    model: 'model.bnen.intgemm.alphas.bin',
    srcVocab: 'vocab.bnen.spm',
    tgtVocab: 'vocab.bnen.spm',
    lex: 'lex.50.50.bnen.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.bulgarian: LanguageFiles(
    model: 'model.bgen.intgemm.alphas.bin',
    srcVocab: 'vocab.bgen.spm',
    tgtVocab: 'vocab.bgen.spm',
    lex: 'lex.50.50.bgen.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.catalan: LanguageFiles(
    model: 'model.caen.intgemm.alphas.bin',
    srcVocab: 'vocab.caen.spm',
    tgtVocab: 'vocab.caen.spm',
    lex: 'lex.50.50.caen.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.chinese: LanguageFiles(
    model: 'model.zhen.intgemm.alphas.bin',
    srcVocab: 'vocab.zhen.spm',
    tgtVocab: 'vocab.zhen.spm',
    lex: 'lex.50.50.zhen.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.croatian: LanguageFiles(
    model: 'model.hren.intgemm.alphas.bin',
    srcVocab: 'vocab.hren.spm',
    tgtVocab: 'vocab.hren.spm',
    lex: 'lex.50.50.hren.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.czech: LanguageFiles(
    model: 'model.csen.intgemm.alphas.bin',
    srcVocab: 'vocab.csen.spm',
    tgtVocab: 'vocab.csen.spm',
    lex: 'lex.50.50.csen.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.danish: LanguageFiles(
    model: 'model.daen.intgemm.alphas.bin',
    srcVocab: 'vocab.daen.spm',
    tgtVocab: 'vocab.daen.spm',
    lex: 'lex.50.50.daen.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.dutch: LanguageFiles(
    model: 'model.nlen.intgemm.alphas.bin',
    srcVocab: 'vocab.nlen.spm',
    tgtVocab: 'vocab.nlen.spm',
    lex: 'lex.50.50.nlen.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.estonian: LanguageFiles(
    model: 'model.eten.intgemm.alphas.bin',
    srcVocab: 'vocab.eten.spm',
    tgtVocab: 'vocab.eten.spm',
    lex: 'lex.50.50.eten.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.finnish: LanguageFiles(
    model: 'model.fien.intgemm.alphas.bin',
    srcVocab: 'vocab.fien.spm',
    tgtVocab: 'vocab.fien.spm',
    lex: 'lex.50.50.fien.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.french: LanguageFiles(
    model: 'model.fren.intgemm.alphas.bin',
    srcVocab: 'vocab.fren.spm',
    tgtVocab: 'vocab.fren.spm',
    lex: 'lex.50.50.fren.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.german: LanguageFiles(
    model: 'model.deen.intgemm.alphas.bin',
    srcVocab: 'vocab.deen.spm',
    tgtVocab: 'vocab.deen.spm',
    lex: 'lex.50.50.deen.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.greek: LanguageFiles(
    model: 'model.elen.intgemm.alphas.bin',
    srcVocab: 'vocab.elen.spm',
    tgtVocab: 'vocab.elen.spm',
    lex: 'lex.50.50.elen.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.gujarati: LanguageFiles(
    model: 'model.guen.intgemm.alphas.bin',
    srcVocab: 'vocab.guen.spm',
    tgtVocab: 'vocab.guen.spm',
    lex: 'lex.50.50.guen.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.hebrew: LanguageFiles(
    model: 'model.heen.intgemm.alphas.bin',
    srcVocab: 'vocab.heen.spm',
    tgtVocab: 'vocab.heen.spm',
    lex: 'lex.50.50.heen.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.hindi: LanguageFiles(
    model: 'model.hien.intgemm.alphas.bin',
    srcVocab: 'vocab.hien.spm',
    tgtVocab: 'vocab.hien.spm',
    lex: 'lex.50.50.hien.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.hungarian: LanguageFiles(
    model: 'model.huen.intgemm.alphas.bin',
    srcVocab: 'vocab.huen.spm',
    tgtVocab: 'vocab.huen.spm',
    lex: 'lex.50.50.huen.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.icelandic: LanguageFiles(
    model: 'model.isen.intgemm.alphas.bin',
    srcVocab: 'vocab.isen.spm',
    tgtVocab: 'vocab.isen.spm',
    lex: 'lex.50.50.isen.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.indonesian: LanguageFiles(
    model: 'model.iden.intgemm.alphas.bin',
    srcVocab: 'vocab.iden.spm',
    tgtVocab: 'vocab.iden.spm',
    lex: 'lex.50.50.iden.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.italian: LanguageFiles(
    model: 'model.iten.intgemm.alphas.bin',
    srcVocab: 'vocab.iten.spm',
    tgtVocab: 'vocab.iten.spm',
    lex: 'lex.50.50.iten.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.japanese: LanguageFiles(
    model: 'model.jaen.intgemm.alphas.bin',
    srcVocab: 'vocab.jaen.spm',
    tgtVocab: 'vocab.jaen.spm',
    lex: 'lex.50.50.jaen.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.kannada: LanguageFiles(
    model: 'model.knen.intgemm.alphas.bin',
    srcVocab: 'vocab.knen.spm',
    tgtVocab: 'vocab.knen.spm',
    lex: 'lex.50.50.knen.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.korean: LanguageFiles(
    model: 'model.koen.intgemm.alphas.bin',
    srcVocab: 'vocab.koen.spm',
    tgtVocab: 'vocab.koen.spm',
    lex: 'lex.50.50.koen.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.latvian: LanguageFiles(
    model: 'model.lven.intgemm.alphas.bin',
    srcVocab: 'vocab.lven.spm',
    tgtVocab: 'vocab.lven.spm',
    lex: 'lex.50.50.lven.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.lithuanian: LanguageFiles(
    model: 'model.lten.intgemm.alphas.bin',
    srcVocab: 'vocab.lten.spm',
    tgtVocab: 'vocab.lten.spm',
    lex: 'lex.50.50.lten.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.malay: LanguageFiles(
    model: 'model.msen.intgemm.alphas.bin',
    srcVocab: 'vocab.msen.spm',
    tgtVocab: 'vocab.msen.spm',
    lex: 'lex.50.50.msen.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.malayalam: LanguageFiles(
    model: 'model.mlen.intgemm.alphas.bin',
    srcVocab: 'vocab.mlen.spm',
    tgtVocab: 'vocab.mlen.spm',
    lex: 'lex.50.50.mlen.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.persian: LanguageFiles(
    model: 'model.faen.intgemm.alphas.bin',
    srcVocab: 'vocab.faen.spm',
    tgtVocab: 'vocab.faen.spm',
    lex: 'lex.50.50.faen.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.polish: LanguageFiles(
    model: 'model.plen.intgemm.alphas.bin',
    srcVocab: 'vocab.plen.spm',
    tgtVocab: 'vocab.plen.spm',
    lex: 'lex.50.50.plen.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.portuguese: LanguageFiles(
    model: 'model.pten.intgemm.alphas.bin',
    srcVocab: 'vocab.pten.spm',
    tgtVocab: 'vocab.pten.spm',
    lex: 'lex.50.50.pten.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.romanian: LanguageFiles(
    model: 'model.roen.intgemm.alphas.bin',
    srcVocab: 'vocab.roen.spm',
    tgtVocab: 'vocab.roen.spm',
    lex: 'lex.50.50.roen.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.russian: LanguageFiles(
    model: 'model.ruen.intgemm.alphas.bin',
    srcVocab: 'vocab.ruen.spm',
    tgtVocab: 'vocab.ruen.spm',
    lex: 'lex.50.50.ruen.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.slovak: LanguageFiles(
    model: 'model.sken.intgemm.alphas.bin',
    srcVocab: 'vocab.sken.spm',
    tgtVocab: 'vocab.sken.spm',
    lex: 'lex.50.50.sken.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.slovenian: LanguageFiles(
    model: 'model.slen.intgemm.alphas.bin',
    srcVocab: 'vocab.slen.spm',
    tgtVocab: 'vocab.slen.spm',
    lex: 'lex.50.50.slen.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.spanish: LanguageFiles(
    model: 'model.esen.intgemm.alphas.bin',
    srcVocab: 'vocab.esen.spm',
    tgtVocab: 'vocab.esen.spm',
    lex: 'lex.50.50.esen.s2t.bin',
    modelType: ModelType.baseMemory,
  ),
  Language.swedish: LanguageFiles(
    model: 'model.sven.intgemm.alphas.bin',
    srcVocab: 'vocab.sven.spm',
    tgtVocab: 'vocab.sven.spm',
    lex: 'lex.50.50.sven.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.tamil: LanguageFiles(
    model: 'model.taen.intgemm.alphas.bin',
    srcVocab: 'vocab.taen.spm',
    tgtVocab: 'vocab.taen.spm',
    lex: 'lex.50.50.taen.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.telugu: LanguageFiles(
    model: 'model.teen.intgemm.alphas.bin',
    srcVocab: 'vocab.teen.spm',
    tgtVocab: 'vocab.teen.spm',
    lex: 'lex.50.50.teen.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.turkish: LanguageFiles(
    model: 'model.tren.intgemm.alphas.bin',
    srcVocab: 'vocab.tren.spm',
    tgtVocab: 'vocab.tren.spm',
    lex: 'lex.50.50.tren.s2t.bin',
    modelType: ModelType.tiny,
  ),
  Language.ukrainian: LanguageFiles(
    model: 'model.uken.intgemm.alphas.bin',
    srcVocab: 'vocab.uken.spm',
    tgtVocab: 'vocab.uken.spm',
    lex: 'lex.50.50.uken.s2t.bin',
    modelType: ModelType.tiny,
  ),
};